FROM alpine:3.13
env DEVOPS="ubuntu"
RUN apk upgrade && export $(cat .env) 
RUN apk add nginx
COPY webfiles/default.conf /etc/nginx/conf.d/default.conf
RUN mkdir -p /var/www/html
WORKDIR /var/www/html
COPY  --chown=nginx:nginx /webfiles/html .
ENTRYPOINT ["./wepage.sh"]
EXPOSE 80
CMD [ "nginx", "-g", "pid /tmp/nginx.pid; daemon off;" ] 

