version: '3'
services:
  webserver:
    restart: always
    build: .
    ports:
      - "80"
    env_file:
      - webserver-env/.env


  java-app:
    restart: always
    container_name: java-app
    image: jetty
    ports:
      - "8080:8080"
    env_file:
      - java-env/.env
    depends_on:
      - docker-mysql
      
  docker-mysql:
    restart: always
    container_name: docker-mysql
    image: mysql
    env_file:
      - db-env/.env
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "6033:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10