name: CI

# Define where the workflow will run on
on:
  # describe which event will trigger the workflow and which branch
  push:
    branches: 
      - master

  # manually run workflow from the actions tab
  workflow_dispatch:

env:
  YEAR: 2022
  DEPLOY_VER: "${{ github.sha }}"


# define the workflow jobs
jobs:
  # This workflow contains 2 jobs called first_job, second_job
  first_job:
    # the runner to run the job on
    runs-on: ubuntu-18.04

    # sequence of task that will run to execute the first_job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Print the list of files/directories in github repository
      - name: Print the list of files/directories in my github repository
        run: |
          git ls-files
      # Print content of your log.txt file.
      - name: Print content of your log.txt file.
        run: |
          cat TASK1/log.txt
          
       # Print commit
      - name: Print commit
        run: |
          echo "Hello from $DEPLOY_VER commit"
      
  second_job:
      runs-on: ubuntu-18.04
      needs: [first_job]
      
      env:
        MONTH: "July"
        
      steps:
      
      - uses: actions/checkout@v3
      
      - name: Idea time
        run: |
          DAY_OF_THE_MONTH=22
          echo "DAY_OF_THE_MONTH=${DAY_OF_THE_MONTH}" >> $GITHUB_ENV
     
      - name: print the system date and time
        run: echo "The currect date and time is $(date +'%Y-%m-%dT%H:%M:%S')"
      
      # Print variable’s content
      - name: Print variable’s content
        run: |
          echo "Day - $DAY_OF_THE_MONTH;"
          echo "Month - $MONTH;"
          echo "Year - $YEAR."
          
      # Print my favorite day of week    
      - name: Print my favorite day of week
        run: |
          echo "My favorite day of week:" 
          echo ${{ secrets.FAVORITE_DAY_OF_WEEK }}
